INSERT INTO jugador(
	nombre_jugador, apellido_jugador, edad_jugador, club_jugador, pais_jugador, posicion_jugador)
	VALUES	('Pedro', 'Gallese', 28, 'Tiburones Rojos', 'Perú', 'Arquero'),
			('Carlos', 'Caceda', 26, 'Deportivo Municipal', 'Perú', 'Arquero'),
			('Jose', 'Carvallo', 32, 'UTC', 'Perú', 'Arquero'),
			('Alberto', 'Rodriguez', 34, 'Junio', 'Perú', 'Defensor'),
			('Aldo', 'Corzo', 29, 'Universitario', 'Perú', 'Defensor'),
			('Anderson', 'Santamaria', 26, 'Puebla', 'Perú', 'Defensor'),
			('Miguel', 'Araujo', 23, 'Alianza Lima', 'Perú', 'Defensor'),
			('Miguel', 'Trauco', 25, 'Flamengo', 'Perú', 'Defensor'),
			('Christian', 'Ramos', 29, 'Tiburones Rojos', 'Perú', 'Defensor'),
			('Luis', 'Advincula', 28, 'Lobos BUAP', 'Perú', 'Defensor'),
			('Nilson', 'Loyola', 23, 'Melgar', 'Perú', 'Defensor'),
			('Paolo', 'Hurtado', 27, 'Vitoria', 'Perú', 'Mediocampista'),
			('Christian', 'Cueva', 26, 'Sao Paulo', 'Perú', 'Mediocampista'),
			('Renato', 'Tapia', 22, 'Feyenoord', 'Perú', 'Mediocampista'),
			('Andy', 'Polo', 23, 'Portland Timbers', 'Perú', 'Mediocampista'),
			('Wilder', 'Cartagena', 23, 'Tiburones Rojos', 'Perú', 'Mediocampista'),
			('Yoshimar', 'Yotun', 28, 'Orlando City', 'Perú', 'Mediocampista'),
			('Pedro', 'Aquino', 23, 'Leon', 'Perú', 'Mediocampista'),
			('Paolo', 'Guerrero', 34, 'Flamengo', 'Perú', 'Mediocampista'),
			('Jefferson', 'Farfan', 33, 'Lokomotiv Moscu', 'Perú', 'Delantero'),
			('Raul', 'Ruidiaz', 27, 'Monarcas Morelia', 'Perú', 'Delantero'),
			('André', 'Carrillo', 27, 'Watford', 'Perú', 'Delantero'),
			('Edison', 'Flores', 24, 'Aalborg', 'Perú', 'Delantero'),
			('Dominik', 'Livakovic', 23, 'Dinamo Zagreb', 'Croacia', 'Arquero'),
			('Lovre', 'Kalinic', 28, 'KAA Gent', 'Croacia', 'Arquero'),
			('Danijel', 'Subasic', 33, 'Monaco', 'Croacia', 'Arquero'),
			('Sime', 'Vrsaljko', 26, 'Atletico Madrid', 'Croacia', 'Defensor'),
			('Ivan', 'Strinic', 30, 'Sampdoria', 'Croacia', 'Defensor'),
			('Vedran', 'Corluka', 32, 'Lokomotiv Moscu', 'Croacia', 'Defensor'),
			('Dejan', 'Lovren', 28, 'Liverpool FC', 'Croacia', 'Defensor'),
			('Tin', 'Jedvaj', 22, 'BayerLeverkusen', 'Croacia', 'Defensor'),
			('Duje', 'Caleta-Car', 21, 'Red Bull Salzburg', 'Croacia', 'Defensor'),
			('Domagoj', 'Vida', 29, 'Besiktas', 'Croacia', 'Defensor'),
			('Josip', 'Pivaric', 29, 'Dinamo Kiev', 'Croacia', 'Defensor'),
			('Ivan', 'Rakitic', 30, 'FC Barcelona', 'Croacia', 'Mediocampista'),
			('Mateo', 'Kovacic', 24, 'Real Madrid', 'Croacia', 'Mediocampista'),
			('Luka', 'Modric', 32, 'Real Madrid', 'Croacia', 'Mediocampista'),
			('Marcelo', 'Brozovic', 25, 'Inter', 'Croacia', 'Mediocampista'),
			('Filip', 'Bradaric', 26, 'HNK Rijeka', 'Croacia', 'Mediocampista'),
			('Milan', 'Badelj', 29, 'Fiorentina', 'Croacia', 'Mediocampista'),
			('Ivan', 'Perisic', 29, 'Inter', 'Croacia', 'Delantero'),
			('Andrej', 'Kramaric', 26, 'TSG Hoffenheim', 'Croacia', 'Delantero'),
			('Nikola', 'Kalinic', 30, 'Milan', 'Croacia', 'Delantero'),
			('Mario', 'Mandzukic', 32, 'Juventus FC', 'Croacia', 'Delantero'),
			('Ante', 'Rebic', 24, 'Eintracht Frankfurt', 'Croacia', 'Delantero'),
			('Marko', 'Pjaca', 23, 'Schalke 04', 'Croacia', 'Delantero'),
			('Hannes', 'Hallorsson', 31, 'Randers FC', 'Islandia', 'Arquero'),
			('Frederik', 'Schram', 23, 'FC Roskilde', 'Islandia', 'Arquero'),
			('Runar', 'Runarsson', 23, 'FC Nordsjaelland', 'Islandia', 'Arquero'),
			('Birkir', 'Svarsson', 33, 'Valur Reykjavik', 'Islandia', 'Defensor'),
			('Sverrir', 'Ingason', 24, 'FC Rostov', 'Islandia', 'Defensor'),
			('Ragnar', 'Sigurdsson', 31, 'FC Rostov', 'Islandia', 'Defensor'),
			('Kari', 'Arnason', 35, 'Aberdeen', 'Islandia', 'Defensor'),
			('Holmar', 'Eyjolfsson', 27, 'Levski Sofia', 'Islandia', 'Defensor'),
			('Horour', 'Magnusson', 25, 'Bristol City', 'Islandia', 'Defensor'),
			('Ari', 'Skulason', 31, 'KSC Lokeren', 'Islandia', 'Defensor'),
			('Samuel', 'Friojonsson', 22, 'Valerenga', 'Islandia', 'Mediocampista'),
			('Albert', 'Gudmundsson', 20, 'PSV Eindhoven', 'Islandia', 'Mediocampista'),
			('Johann', 'Bjarnason', 27, 'Burnley', 'Islandia', 'Mediocampista'),
			('Birkir', 'Guomundsson', 30, 'Aston Vila', 'Islandia', 'Mediocampista'),
			('Gylfi', 'Sigurdson', 28, 'Everton FC', 'Islandia', 'Mediocampista'),
			('Olafur', 'Skulason', 35, 'Kardemir Karabukspor', 'Islandia', 'Mediocampista'),
			('Aron', 'Gunnarsson', 29, 'Cadiff City', 'Islandia', 'Mediocampista'),
			('Rurik', 'Gislason', 30, 'SV Sandhausen', 'Islandia', 'Mediocampista'),
			('Emil', 'Hallfredsson', 33, 'Udinese', 'Islandia', 'Mediocampista'),
			('Arnor', 'Traustason', 25, 'Malmo', 'Islandia', 'Mediocampista'),
			('Bjorn', 'Sigurdarson', 27, 'FC Rostov', 'Islandia', 'Delantero'),
			('Alfred', 'Finnbogason', 29, 'FC Augsburg', 'Islandia', 'Delantero'),
			('Jon', 'Boovarsson', 26, 'Reading', 'Islandia', 'Delantero'),
			('Ikechukwu', 'Ezenwa', 29, 'Enyimba', 'Nigeria', 'Arquero'),
			('Daniel', 'Akpeyi', 32, 'Chippa United', 'Nigeria', 'Arquero'),
			('Francis', 'Uzoho', 19, 'Deportivo La Coruña', 'Nigeria', 'Arquero'),
			('Brian', 'Idowu', 26, 'Amkar Perm', 'Nigeria', 'Defensor'),
			('Elderson', 'Echiejile', 30, 'Cercle Brugge', 'Nigeria', 'Defensor'),
			('William', 'Troost-Ekong', 24, 'Bursaspor', 'Nigeria', 'Defensor'),
			('Leon', 'Balogun', 29, 'FSV Mainz', 'Nigeria', 'Defensor'),
			('Abdullahi', 'Shehu', 25, 'Bursaspor', 'Nigeria', 'Defensor'),
			('Chidozie', 'Awaziem', 21, 'FC Nantes', 'Nigeria', 'Defensor'),
			('Tyronne', 'Ebuehi', 22, 'ADO La Haya', 'Nigeria', 'Defensor'),
			('Kenneth', 'Omeruo', 24, 'Kasimpasa', 'Nigeria', 'Defensor'),
			('Wilfred', 'Ndidi', 21, 'Leicester City', 'Nigeria', 'Mediocampista'),
			('Oghenekaro', 'Etebo', 22, 'Las Palmas', 'Nigeria', 'Mediocampista'),
			('John', 'Obi Mikel', 31, 'Tianjin Teda', 'Nigeria', 'Mediocampista'),
			('Joel', 'Obi', 27, 'Torino', 'Nigeria', 'Mediocampista'),
			('Ogenyi', 'Onazi', 25, 'Trabzonspor', 'Nigeria', 'Mediocampista'),
			('John', 'Ogu', 30, 'Hapoel Beer Sheva', 'Nigeria', 'Mediocampista'),
			('Ahmed', 'Musa', 25, 'CSKA Moscu', 'Nigeria', 'Delantero'),
			('Odion', 'Ighalo', 28, 'Changchun Yatai', 'Nigeria', 'Delantero'),
			('Victor', 'Moses', 27, 'Chelsea FC', 'Nigeria', 'Delantero'),
			('Simeon', 'Nwankwo', 26, 'FC Crotone', 'Nigeria', 'Delantero'),
			('Kelechi', 'Iheanacho', 22, 'Leicester City', 'Nigeria', 'Delantero'),
			('Alex', 'Iwobi', 22, 'Arsenal FC', 'Nigeria', 'Delantero'),
			('Guillermo', 'Ochoa', 32, 'Standard Lieje', 'México', 'Arquero'),
			('Jose de Jesus', 'Corona', 34, 'Cruz Azul', 'México', 'Arquero'),
			('Alfredo', 'Talavera', 35, 'Toluca', 'México', 'Arquero'),
			('Rafael', 'Marquez', 39, 'Atlas', 'México', 'Defensor'),
			('Hector', 'Moreno', 30, 'Real Sociedad', 'México', 'Defensor'),
			('Miguel', 'Layun', 29, 'Sevilla FC', 'México', 'Defensor'),
			('Hugo', 'Ayala', 30, 'Tigres', 'México', 'Defensor'),
			('Carlos', 'Salcedo', 24, 'Eintracht Frankfurt', 'México', 'Defensor'),
			('Jesus', 'Gallardo', 23, 'Universidad Nacional', 'México', 'Defensor'),
			('Edson', 'Alvarez', 20, 'America', 'México', 'Defensor'),
			('Erick', 'Gutierrez', 23, 'Pachuca', 'México', 'Mediocampista'),
			('Andres', 'Guardado', 31, 'Betis', 'México', 'Mediocampista'),
			('Hector', 'Herrera', 27, 'Porto', 'México', 'Mediocampista'),
			('Javier', 'Aquino', 28, 'Tigres', 'México', 'Mediocampista'),
			('Marco', 'Fabian', 28, 'Eintracht Frankfurt', 'México', 'Mediocampista'),
			('Jonathan', 'Dos Santos', 28, 'Los Angeles Galaxy', 'México', 'Mediocampista'),
			('Giovani', 'Dos Santos', 29, 'Los Angeles Galaxy', 'México', 'Delantero'),
			('Javier', 'Hernandez', 29, 'West Ham', 'México', 'Delantero'),
			('Carlos', 'Vela', 28, 'Los Angeles FC', 'México', 'Delantero'),
			('Orie', 'Peralta', 34, 'America', 'México', 'Delantero'),
			('Raul', 'Jimenez', 26, 'Benfica', 'México', 'Delantero'),
			('Jesus', 'Corona', 25, 'Porto', 'México', 'Delantero'),
			('Hirving', 'Lozano', 22, 'PSV Eindhoven', 'México', 'Delantero'),
			('Thibaut', 'Courtois', 26, 'Chelsea FC', 'Bélgica', 'Arquero'),
			('Simon', 'Mignolet', 30, 'Liverpool FC', 'Bélgica', 'Arquero'),
			('Koen', 'Casteels', 25, 'Vlf Wolsburg', 'Bélgica', 'Arquero'),
			('Toby', 'Alderweireld', 29, 'Tottenham', 'Bélgica', 'Defensor'),
			('Thomas', 'Vermaelen', 32, 'FC Barcelona', 'Bélgica', 'Defensor'),
			('Vincent', 'Kompany', 32, 'Manchester City', 'Bélgica', 'Defensor'),
			('Jan', 'Vertonghen', 31, 'Tottenham', 'Bélgica', 'Defensor'),
			('Thomas', 'Meunier', 26, 'Paris Saint Germain', 'Bélgica', 'Defensor'),
			('Dedryck', 'Boyata', 27, 'Celtic ', 'Bélgica', 'Defensor'),
			('Leander', 'Dendoncker', 23, 'RSC Anderlecht', 'Bélgica', 'Defensor'),
			('Axel', 'Witsel', 29, 'Tianjin Quanjian', 'Bélgica', 'Mediocampista'),
			('Kevin', 'De Bruyne', 26, 'Manchester City', 'Bélgica', 'Mediocampista'),
			('Marouane', 'Fellaini', 30, 'Manchester United', 'Bélgica', 'Mediocampista'),
			('Yannick', 'Carrasco', 24, 'Dalian Yifang', 'Bélgica', 'Mediocampista'),
			('Thorgan', 'Hazard', 25, 'Borussia Monchengladbach', 'Bélgica', 'Mediocampista'),
			('Youri', 'Tielemans', 21, 'Monaco', 'Bélgica', 'Mediocampista'),
			('Mousa', 'Dembele', 30, 'Tottenham', 'Bélgica', 'Mediocampista'),
			('Nacer', 'Chadli', 28, 'West Bromwich', 'Bélgica', 'Mediocampista'),
			('Romelu', 'Lukaku', 25, 'Manchester United', 'Bélgica', 'Delantero'),
			('Eden', 'Hazard', 27, 'Chelsea FC', 'Bélgica', 'Delantero'),
			('Dries', 'Mertens', 31, 'Napoli', 'Bélgica', 'Delantero'),
			('Adnan', 'Januzaj', 23, 'Real Sociedad', 'Bélgica', 'Delantero'),
			('Michy', 'Batshuayi', 24, 'Borussia Dortmund', 'Bélgica', 'Delantero'),
			('Jordan', 'Pickford', 24, 'Everton FC', 'Inglaterra', 'Arquero'),
			('Jack', 'Butland', 25, 'Stoke City', 'Inglaterra', 'Arquero'),
			('Nick', 'Pope', 26, 'Burnley', 'Inglaterra', 'Arquero'),
			('Kyle', 'Walker', 28, 'Manchester City', 'Inglaterra', 'Defensor'),
			('Danny', 'Rose', 27, 'Tottenham', 'Inglaterra', 'Defensor'),
			('John', 'Stones', 24, 'Manchester City', 'Inglaterra', 'Defensor'),
			('Harry', 'Maguire', 25, 'Leicester City', 'Inglaterra', 'Defensor'),
			('Kieran', 'Trippier', 27, 'Tottenham', 'Inglaterra', 'Defensor'),
			('Gary', 'Cahill', 32, 'Chelsea FC', 'Inglaterra', 'Defensor'),
			('Phil', 'Jones', 26, 'Manchester United', 'Inglaterra', 'Defensor'),
			('Fabian', 'Delph', 28, 'Manchester City', 'Inglaterra', 'Defensor'),
			('Ashley', 'Young', 32, 'Manchester United', 'Inglaterra', 'Defensor'),
			('Trent', 'Alexander-Arnold', 19, 'Liverpool FC', 'Inglaterra', 'Defensor'),
			('Eric', 'Dier', 24, 'Tottenham', 'Inglaterra', 'Mediocampista'),
			('Jesse', 'Lingard', 25, 'Manchester United', 'Inglaterra', 'Mediocampista'),
			('Jordan', 'Henderson', 27, 'Liverpool FC', 'Inglaterra', 'Mediocampista'),
			('Dele', 'Alli', 22, 'Tottenham', 'Inglaterra', 'Mediocampista'),
			('Ruben', 'Loftus-Cheek', 22, 'Crystal Palace', 'Inglaterra', 'Mediocampista'),
			('Harry', 'Kane', 24, 'Tottenham', 'Inglaterra', 'Delantero'),
			('Raheem', 'Sterling', 23, 'Manchester City', 'Inglaterra', 'Delantero'),
			('Jamie', 'Vardy', 31, 'Leicester City', 'Inglaterra', 'Delantero'),
			('Danny', 'Welbeck', 27, 'Arsenal FC', 'Inglaterra', 'Delantero'),
			('Marcus', 'Rashford', 20, 'Manchester United', 'Inglaterra', 'Delantero'),
			('David', 'Ospina', 29, 'Arsenal FC', 'Colombia', 'Arquero'),
			('Camilo', 'Vargas', 29, 'Deportivo Cali', 'Colombia', 'Arquero'),
			('Jose Fernando', 'Cuadrado', 32, 'Once Caldas', 'Colombia', 'Arquero'),
			('Cristian', 'Zapata', 31, 'Milan', 'Colombia', 'Defensor'),
			('Oscar', 'Murillo', 30, 'Pachuca', 'Colombia', 'Defensor'),
			('Santiago', 'Arias', 26, 'PSV Eindhoven', 'Colombia', 'Defensor'),
			('Yerry', 'Mina', 23, 'FC Barcelona', 'Colombia', 'Defensor'),
			('Farid', 'Diaz', 34, 'Olimpia', 'Colombia', 'Defensor'),
			('Davinson', 'Sanchez', 22, 'Tottenham', 'Colombia', 'Defensor'),
			('Johan', 'Mojica', 25, 'Girona', 'Colombia', 'Defensor'),
			('Wilmar', 'Barrios', 24, 'Boca Juniors', 'Colombia', 'Mediocampista'),
			('Carlos', 'Sanchez', 32, 'Espanyol', 'Colombia', 'Mediocampista'),
			('Abel', 'Aguilar', 33, 'Deportivo Cali', 'Colombia', 'Mediocampista'),
			('James', 'Rodriguez', 26, 'Bayern Munich', 'Colombia', 'Mediocampista'),
			('Juan Fernando', 'Quintero', 25, 'River Plate', 'Colombia', 'Mediocampista'),
			('Mateus', 'Uribe', 27, 'America', 'Colombia', 'Mediocampista'),
			('Jefferson', 'Lerma', 23, 'Levante', 'Colombia', 'Mediocampista'),
			('Juan Guillermo', 'Cuadrado', 29, 'Juventus FC', 'Colombia', 'Mediocampista'),
			('Carlos', 'Bacca', 31, 'Villareal', 'Colombia', 'Delantero'),
			('Radamel', 'Falcao', 32, 'Monaco', 'Colombia', 'Delantero'),
			('Luis', 'Muriel', 27, 'Sevilla FC', 'Colombia', 'Delantero'),
			('Miguel', 'Borja', 25, 'Palmeiras', 'Colombia', 'Delantero'),
			('Jose', 'Izquierdo', 25, 'Brighton', 'Colombia', 'Delantero'),
			('Vladimir', 'Stojkovic', 34, 'Partizan', 'Serbia', 'Arquero'),
			('Predrag', 'Rajkovic', 22, 'Maccabi Tel Aviv', 'Serbia', 'Arquero'),
			('Marko', 'Dmitrovic', 26, 'Eibar', 'Serbia', 'Arquero'),
			('Antonio', 'Rukavina', 34, 'Villareal', 'Serbia', 'Defensor'),
			('Dusko', 'Tosic', 33, 'Besiktas', 'Serbia', 'Defensor'),
			('Uros', 'Spajic', 25, 'RSC Anderlecht', 'Serbia', 'Defensor'),
			('Branislav', 'Ivanovic', 34, 'Zenit de San Petersburgo', 'Serbia', 'Defensor'),
			('Aleksandar', 'Kolarov', 32, 'Roma', 'Serbia', 'Defensor'),
			('Milos', 'Veljkovic', 22, 'Werder Bremen', 'Serbia', 'Defensor'),
			('Milan', 'Rodic', 27, 'Estrella Roja', 'Serbia', 'Defensor'),
			('Nikola', 'Milenkovic', 20, 'Fiorentina', 'Serbia', 'Defensor'),
			('Luka', 'Milivojevic', 27, 'Crystal Palace', 'Serbia', 'Mediocampista'),
			('Andrija', 'Zivkovic', 21, 'Benfica', 'Serbia', 'Mediocampista'),
			('Dusan', 'Tadic', 29, 'Southampton', 'Serbia', 'Mediocampista'),
			('Marko', 'Grujic', 22, 'Cardiff', 'Serbia', 'Mediocampista'),
			('Filip', 'Kostic', 25, 'Hamburgo', 'Serbia', 'Mediocampista'),
			('Sergej', 'Milinkovic-Savic', 23, 'Lazio', 'Serbia', 'Mediocampista'),
			('Nemanja', 'Matic', 29, 'Manchester United', 'Serbia', 'Mediocampista'),
			('Adem', 'Ljajic', 26, 'Torino', 'Serbia', 'Mediocampista'),
			('Aleksandar', 'Prijovic', 28, 'PAOK Salonica', 'Serbia', 'Delantero'),
			('Aleksandar', 'Mitrovic', 23, 'Fulham', 'Serbia', 'Delantero'),
			('Nemanja', 'Radonjic', 22, 'Estrella Roja', 'Serbia', 'Delantero'),
			('Luka', 'Jovic', 20, 'Eintracht Frankfurt', 'Serbia', 'Delantero'),
			('Wojciech', 'Szczesny', 28, 'Juventus FC', 'Polonia', 'Arquero'),
			('Bartosz', 'Bialkowski', 30, 'Ipswich Town', 'Polonia', 'Arquero'),
			('Lukasz', 'Fabianski', 33, 'Swansea City', 'Polonia', 'Arquero'),
			('Michal', 'Pazdan', 30, 'Legia Varsovia', 'Polonia', 'Defensor'),
			('Artur', 'Jedrzejczyk', 30, 'Legia Varsovia', 'Polonia', 'Defensor'),
			('Thiago', 'Cionek', 32, 'SPAL', 'Polonia', 'Defensor'),
			('Jan', 'Bednarek', 22, 'Southampton', 'Polonia', 'Defensor'),
			('Kamil', 'Glik', 30, 'Monaco', 'Polonia', 'Defensor'),
			('Bartosz', 'Bereszynski', 25, 'Sampdoria', 'Polonia', 'Defensor'),
			('Lukasz', 'Piszczek', 33, 'Borussia Dortmund', 'Polonia', 'Defensor'),
			('Jacek', 'Goralski', 25, 'Lodogorets', 'Polonia', 'Mediocampista'),
			('Karol', 'Linetty', 23, 'Sampdoria', 'Polonia', 'Mediocampista'),
			('Grzegorz', 'Krychowiak', 28, 'West Bromwich', 'Polonia', 'Mediocampista'),
			('Kamil', 'Grosicki', 3, 'Hull City', 'Polonia', 'Mediocampista'),
			('Maciej', 'Rybus', 28, 'Lokomotiv Moscu', 'Polonia', 'Mediocampista'),
			('Jakub', 'Baszczykowski', 32, 'Vfl Wolfsburg', 'Polonia', 'Mediocampista'),
			('Slawomir', 'Peszko', 33, 'Lechia Gdansk', 'Polonia', 'Mediocampista'),
			('Piotr', 'Zielinski', 24, 'Napoli', 'Polonia', 'Mediocampista'),
			('Rafal', 'Kurzawa', 25, 'Gornik Zabrze', 'Polonia', 'Mediocampista'),
			('Arkadiusz', 'Milik', 24, 'Napoli', 'Polonia', 'Delantero'),
			('Robert', 'Lewandowski', 29, 'Bayern Munich', 'Polonia', 'Delantero'),
			('Lukasz', 'Teodorczyk', 27, 'RSC Anderlecht', 'Polonia', 'Delantero'),
			('Dawid', 'Kownacki', 21, 'Sampdoria', 'Polonia', 'Delantero'),
			('Eiji', 'Kawasaki', 35, 'FC Metz', 'Japón', 'Arquero'),
			('Masaaki', 'Higashiguchi', 32, 'Gamba Osaka', 'Japón', 'Arquero'),
			('Kosuke', 'Nakamura', 23, 'Kashiwa Reysol', 'Japón', 'Arquero'),
			('Naomichi', 'Ueda', 23, 'Kashima Antlers', 'Japón', 'Defensor'),
			('Gen', 'Shoji', 25, 'Kashima Antlers', 'Japón', 'Defensor'),
			('Yuto', 'Nagatomo', 31, 'Galatasaray', 'Japón', 'Defensor'),
			('Wataru', 'Endo', 25, 'Urawa Red Diamonds', 'Japón', 'Defensor'),
			('Hiroki', 'Sakai', 28, 'Olympique Marseille', 'Japón', 'Defensor'),
			('Tomoaki', 'Makino', 31, 'Urawa Red Diamonds', 'Japón', 'Defensor'),
			('Gotoku', 'Sakai', 27, 'Hamburgo SV', 'Japón', 'Defensor'),
			('Maya', 'Yoshida', 29, 'Southampton', 'Japón', 'Defensor'),
			('Keisuke', 'Honda', 32, 'Pachuca', 'Japón', 'Mediocampista'),
			('Gaku', 'Shibasaki', 26, 'Getafe', 'Japón', 'Mediocampista'),
			('Genki', 'Haraguchi', 27, 'Fortuna Dusseldorf', 'Japón', 'Mediocampista'),
			('Shinji', 'Kagawa', 29, 'Borussia Dortmund', 'Japón', 'Mediocampista'),
			('Takashi', 'Usami', 26, 'Fortuna Dusseldorf', 'Japón', 'Mediocampista'),
			('Takashi', 'Inui', 30, 'Eibar', 'Japón', 'Mediocampista'),
			('Hotaru', 'Yamaguchi', 27, 'Cerezo Osaka', 'Japón', 'Mediocampista'),
			('Makoto', 'Hasebe', 34, 'Eintracht Frankfurt', 'Japón', 'Mediocampista'),
			('Ryota', 'Oshima', 25, 'Kawasaki Frontale', 'Japón', 'Mediocampista'),
			('Shinji', 'Okazaki', 32, 'Leicester City', 'Japón', 'Delantero'),
			('Yoshinori', 'Muto', 25, 'Mainz', 'Japón', 'Delantero'),
			('Yuya', 'Osako', 28, 'FC Koln', 'Japón', 'Delantero')
