INSERT INTO jugador(
	nombre_jugador, apellido_jugador, edad_jugador, pais_jugador, club_jugador, posicion_jugador)
	VALUES  ('Jefferson', NULL, 36, 'Brasil', 'Botafogo', 'Arquero'),
			('Julio Cesar', NULL, 38, 'Brasil', 'Retirado', 'Arquero'),
			('Alisson', NULL, 25, 'Brasil', 'Roma', 'Arquero'),
			('Cassio', NULL, 31, 'Brasil', 'Corinthians', 'Arquero'),
			('Ederson', NULL, 24, 'Brasil', 'Manchester City', 'Arquero'),
			('Dani', 'Alves', 35, 'Brasil', 'Paris Saint Germain', 'Defensor'),
			('Thiago', 'Silva', 35, 'Brasil', 'Paris Saint Germain', 'Defensor'),
			('David', 'Luiz', 31, 'Brasil', 'Chelsea FC', 'Defensor'),
			('Marcelo', NULL, 30, 'Brasil', 'Real Madrid', 'Defensor'),
			('Dante', NULL, 34, 'Brasil', 'OGC Niza', 'Defensor'),
			('Maxwell', NULL, 32, 'Brasil', 'Retirado', 'Defensor'),
			('Henrique', NULL, 31, 'Brasil', 'Fluminense', 'Defensor'),
			('Joao', 'Miranda', 33, 'Brasil', 'Inter', 'Defensor'),
			('Geromel', NULL, 32, 'Brasil', 'Gremio', 'Defensor'),
			('Filipe', 'Luis', 32, 'Brasil', 'Atlético Madrid', 'Defensor'),
			('Marquinhos', NULL, 24, 'Brasil', 'Paris Saint Germain', 'Defensor'),
			('Danilo', NULL, 26, 'Brasil', 'Manchester City', 'Defensor'),
			('Fagner', NULL, 29, 'Brasil', 'Corinthians', 'Defensor'),
			('Fernandinho', NULL, 33, 'Brasil', 'Manchester City', 'Mediocampista'),
			('Paulinho', NULL, 29, 'Brasil', 'FC Barcelona', 'Mediocampista'),
			('Oscar', NULL, 26, 'Brasil', 'Shangai SIPG', 'Mediocampista'),
			('Ramires', NULL, 31, 'Brasil', 'Jiangsu Suning', 'Mediocampista'),
			('Luiz', 'Gustavo', 30, 'Brasil', 'Olympique Marseille', 'Mediocampista'),
			('Willian', NULL, 29, 'Brasil', 'Chelsea FC', 'Mediocampista'),
			('Casemiro', NULL, 26, 'Brasil', 'Real Madrid', 'Mediocampista'),
			('Renato', 'Augusto', 30, 'Brasil', 'Beijing Guoan', 'Mediocampista'),
			('Philippe', 'Coutinho', 26, 'Brasil', 'FC Barcelona', 'Mediocampista'),
			('Fred', NULL, 25, 'Brasil', 'Shaktar Donetsk', 'Mediocampista'),
			('Hulk', NULL, 31, 'Brasil', 'Shangai SIPG', 'Delantero'),
			('Fred', NULL, 34, 'Brasil', 'Cruzeiro', 'Delantero'),
			('Neymar', NULL, 26, 'Brasil', 'Paris Saint Germain', 'Delantero'),
			('Hernanes', NULL, 33, 'Brasil', 'Sao Paulo', 'Delantero'),
			('Bernard', NULL, 25, 'Brasil', 'Shaktar Donetsk', 'Delantero'),
			('Douglas', 'Costa', 27, 'Brasil', 'Juventus FC', 'Delantero'),
			('Gabriel', 'Jesus', 21, 'Brasil', 'Manchester City', 'Delantero'),
			('Roberto', 'Firmino', 26, 'Brasil', 'Liverpool FC', 'Delantero'),
			('Taison', NULL, 30, 'Brasil', 'Shaktar Donetsk', 'Delantero'),
			('Sergio', 'Romero', 31, 'Argentina', 'Manchester United', 'Arquero'),
			('Agustín', 'Orión', 36, 'Argentina', 'Colo-Colo', 'Arquero'),
			('Mariano', 'Andújar', 34, 'Argentina', 'Estudiantes de La Plata', 'Arquero'),
			('Franco', 'Armani', 31, 'Argentina', 'River Plate', 'Arquero'),
			('Wilfredo', 'Caballero', 36, 'Argentina', 'Chelsea FC', 'Arquero'),
			('Nahuel', 'Guzmán', 32, 'Argentina', 'Tigres', 'Arquero'),
			('Pablo', 'Zabaleta', 33, 'Argentina', 'West Ham', 'Defensor'),
			('Hugo', 'Campagnaro', 37, 'Argentina', 'Pescara', 'Defensor'),
			('Ezequiel', 'Garay', 31, 'Argentina', 'Valencia', 'Defensor'),
			('Martin', 'Demichelis', 37, 'Argentina', 'Retirado', 'Defensor'),
			('Marcos', 'Rojo', 27, 'Argentina', 'Manchester United', 'Defensor'),
			('Federico', 'Fernandez', 29, 'Argentina', 'Swansea', 'Defensor'),
			('Jose', 'Basanta', 34, 'Argentina', 'Monterrey', 'Defensor'),
			('Nicolás', 'Otamendi', 30, 'Argentina', 'Manchester City', 'Defensor'),
			('Gabriel', 'Mercado', 31, 'Argentina', 'Sevilla FC', 'Defensor'),
			('Nicolás', 'Tagliafico', 25, 'Argentina', 'Ajax FC', 'Defensor'),
			('Cristian', 'Ansaldi', 27, 'Argentina', 'Torino', 'Defensor'),
			('Federico', 'Fazio', 31, 'Argentina', 'Roma FC', 'Defensor'),
			('Marcos', 'Acuña', 26, 'Argentina', 'Sporting Lisboa', 'Mediocampista'),
			('Fernando', 'Gago', 32, 'Argentina', 'Boca Juniors', 'Mediocampista'),
			('Lucas', 'Biglia', 32, 'Argentina', 'Milan FC', 'Mediocampista'),
			('Javier', 'Mascherano', 34, 'Argentina', 'Hebei Fortune', 'Mediocampista'),
			('Angel', 'Di María', 30, 'Argentina', 'Paris Saint Germain', 'Mediocampista'),
			('Ricardo', 'Alvarez', 30, 'Argentina', 'Atlas de Guadalajara', 'Mediocampista'),
			('Augusto', 'Fernandez', 32, 'Argentina', 'Beijing Renhe', 'Mediocampista'),
			('Maximiliano', 'Rodriguez', 37, 'Argentina', 'Peñarol', 'Mediocampista'),
			('Enzo', 'Perez', 32, 'Argentina', 'River Plate', 'Mediocampista'),
			('Ever', 'Banega', 29, 'Argentina', 'Sevilla FC', 'Mediocampista'),
			('Maximiliano', 'Meza', 26, 'Argentina', 'Independiente', 'Mediocampista'),
			('Eduardo', 'Salvio', 28, 'Argentina', 'Benfica', 'Mediocampista'),
			('Giovanni', 'Lo Celso', 22, 'Argentina', 'Paris Saint Germain', 'Mediocampista'),	
			('Cristian', 'Pavon', 22, 'Argentina', 'Boca Juniors', 'Mediocampista'),
			('Lionel', 'Messi', 30, 'Argentina', 'FC Barcelona', 'Delantero'),
			('Gonzalo', 'Higuain', 30, 'Argentina', 'Juventus FC', 'Delantero'),
			('Sergio', 'Agüero', 30, 'Argentina', 'Manchester City', 'Delantero'),
			('Ezequiel', 'Lavezzi', 33, 'Argentina', 'Hebei Fortune', 'Delantero'),
			('Rodrigo', 'Palacio', 36, 'Argentina', 'Bologna FC', 'Delantero'),
			('Paulo', 'Dybala', 24, 'Argentina', 'Juventus FC', 'Delantero'),
			('Mauro', 'Icardi', 25, 'Argentina', 'Inter', 'Delantero'),
			('Lautaro', 'Martínez', 20, 'Argentina', 'Inter', 'Delantero'),
			('Manuel', 'Lanzini', 25, 'Argentina', 'West Ham', 'Mediocampista'),
			('Pablo', 'Perez', 32, 'Argentina', 'Boca Juniors', 'Mediocampista'),
			('Guido', 'Pizarro', 28, 'Argentina', 'Sevilla FC', 'Mediocampista'),
			('Ramiro', 'Funes Mori', 27, 'Argentina', 'Everton FC', 'Defensor'),
			('Germán', 'Pezzella', 26, 'Argentina', 'Fiorentina FC', 'Defensor'),
			('Manuel', 'Neuer', 32, 'Alemania', 'Bayern Munich', 'Arquero'),
			('Roman', 'Weidenfeller', 37, 'Alemania', 'Retirado', 'Arquero'),
			('Ron-Robert', 'Zieler', 29, 'Alemania', 'Stuttgart', 'Arquero'),
			('Kevin', 'Trapp', 27, 'Alemania', 'Paris Saint Germain', 'Arquero'),
			('Marc-Andre', 'ter Stegen', 26, 'Alemania', 'FC Barcelona', 'Arquero'),
			('Kevin', 'Großkreutz', 29, 'Alemania', 'SV Darmstadt 98', 'Defensor'),
			('Benedikt', 'Howedes', 30, 'Alemania', 'Juventus FC', 'Defensor'),
			('Mats', 'Hummels', 29, 'Alemania', 'Bayern Munich', 'Defensor'),
			('Erik', 'Durm', 26, 'Alemania', 'Borussia Dortmund', 'Defensor'),
			('Philipp', 'Lahm', 34, 'Alemania', 'Retirado', 'Defensor'),
			('Per', 'Mertesacker', 33, 'Alemania', 'Arsenal FC', 'Defensor'),
			('Jerome', 'Boateng', 29, 'Alemania', 'Bayern Munich', 'Defensor'),
			('Shkrodan', 'Mustafi', 26, 'Alemania', 'Arsenal FC', 'Defensor'),
			('Marvin', 'Plattenhardt', 26, 'Alemania', 'Hertha Berlin', 'Defensor'),
			('Jonas', 'Hector', 28, 'Alemania', 'FC Koln', 'Defensor'),
			('Niklas', 'Sule', 22, 'Alemania', 'Bayern Munich', 'Defensor'),
			('Antonio', 'Rudiger', 25, 'Alemania', 'Chelsea FC', 'Defensor'),
			('Joshua', 'Kimmich', 23, 'Alemania', 'Bayern Munich', 'Defensor'),
			('Cristoph', 'Kramer', 27, 'Alemania', 'Borussia Monchengladbach', 'Mediocampista'),
			('Mario', 'Gotze', 26, 'Alemania', 'Borussia Dortmund', 'Mediocampista'),
			('Toni', 'Kroos', 28, 'Alemania', 'Real Madrid', 'Mediocampista'),
			('Julian', 'Draxler', 24, 'Alemania', 'Paris Saint Germain', 'Mediocampista'),
			('Mesut', 'Ozil', 29, 'Alemania', 'Arsenal FC', 'Mediocampista'),
			('Bastian', 'Schwensteiger', 32, 'Alemania', 'Chicago Fire', 'Mediocampista'),
			('Sami', 'Khedira', 31, 'Alemania', 'Juventus FC', 'Mediocampista'),
			('Matthias', 'Ginter', 24, 'Alemania', 'Borussia Monchengladbach', 'Mediocampista'),
			('Leon', 'Goretzka', 23, 'Alemania', 'Bayern Munich', 'Mediocampista'),
			('Sebastian', 'Rudy', 28, 'Alemania', 'Bayern Munich', 'Mediocampista'),
			('Julian', 'Brandt', 22, 'Alemania', 'Bayer Leverkusen', 'Mediocampista'),
			('Ilkay', 'Gundogan', 27, 'Alemania', 'Manchester City', 'Mediocampista'),
			('Thomas', 'Muller', 28, 'Alemania', 'Bayern Munich', 'Delantero'),
			('Miroslav', 'Klose', 40, 'Alemania', 'Retirado', 'Delantero'),
			('Lukas', 'Podolski', 33, 'Alemania', 'Vissel Kobe', 'Delantero'),
			('Andre', 'Schurrle', 27, 'Alemania', 'Borussia Dortmund', 'Delantero'),
			('Timo', 'Werner', 22, 'Alemania', 'RB Leipzig', 'Delantero'),
			('Marco', 'Reus', 29, 'Alemania', 'Borussia Dortmund', 'Delantero'),
			('Mario', 'Gomez', 32, 'Alemania', 'Stuttgart', 'Delantero'),
			('Rui', 'Patricio', 30, 'Portugal', 'Sporting Lisboa', 'Arquero'),
			('Anthony', 'Lopes', 27, 'Portugal', 'Olympique Lyon', 'Arquero'),
			('Beto', NULL, 36, 'Portugal', 'Goztepe SK', 'Arquero'),
			('Bruno', 'Alves', 36, 'Portugal', 'Rangers FC', 'Defensor'),
			('Pepe', NULL, 35, 'Portugal', 'Besiktas', 'Defensor'),
			('Raphael', 'Guerreiro', 24, 'Portugal', 'Borussia Dortmund', 'Defensor'),
			('Jose', 'Fonte', 34, 'Portugal', 'Dalian Yifang', 'Defensor'),
			('Ruben', 'Dias', 21, 'Portugal', 'Benfica', 'Defensor'),
			('Ricardo', 'Pereira', 24, 'Portugal', 'Leicester City', 'Defensor'),
			('Mario', 'Rui', 27, 'Portugal', 'Napoli', 'Defensor'),
			('Cedric', 'Soares', 26, 'Portugal', 'Southampton', 'Defensor'),
			('Manuel', 'Fernandes', 31, 'Portugal', 'Lokomotiv', 'Mediocampista'),
			('Joao', 'Moutinho', 23, 'Portugal', 'Monaco', 'Mediocampista'),
			('Joao', 'Mario', 26, 'Portugal', 'West Ham', 'Mediocampista'),
			('William', 'Carvalho', 23, 'Portugal', 'Sporting Lisboa', 'Mediocampista'),
			('Bruno', 'Fernandes', 29, 'Portugal', 'Sporting Lisboa', 'Mediocampista'),
			('Adrien', 'Silva', 11, 'Portugal', 'Leicester City', 'Mediocampista'),
			('Cristiano', 'Ronaldo', 33, 'Portugal', 'Real Madrid', 'Delantero'),
			('André', 'Silva', 23, 'Portugal', 'Milan', 'Delantero'),
			('Bernardo', 'Silva', 23, 'Portugal', 'Manchester City', 'Delantero'),
			('Gonzalo', 'Guedes', 21, 'Portugal', 'Valencia', 'Delantero'),
			('Gelson', 'Martins', 25, 'Portugal', 'Sporting Lisboa', 'Delantero'),
			('Ricardo', 'Quaresma', 34, 'Portugal', 'Besiktas', 'Delantero'),
			('David', 'de Gea', 27, 'España', 'Manchester United', 'Arquero'),
			('Kepa', 'Arrizabalaga', 23, 'España', 'Athletic Club', 'Arquero'),
			('José', 'Reina', 35, 'España', 'Napoli', 'Arquero'),
			('Dani', 'Carvajal', 26, 'España', 'Real Madrid', 'Defensor'),
			('Gerard', 'Piqué', 31, 'España', 'FC Barcelona', 'Defensor'),
			('Nacho', 'Fernandez', 28, 'España', 'Real Madrid', 'Defensor'),
			('Alvaro', 'Odriozola', 22, 'España', 'Real Sociedad', 'Defensor'),
			('Cesar', 'Azpillicueta', 28, 'España', 'Chelsea FC', 'Defensor'),
			('Sergio', 'Ramos', 32, 'España', 'Real Madrid', 'Defensor'),
			('Nacho', 'Monreal', 32, 'España', 'Arsenal FC', 'Defensor'),
			('Jordi', 'Alba', 29, 'España', 'FC Barcelona', 'Defensor'),
			('Sergio', 'Busquets', 29, 'España', 'FC Barcelona', 'Mediocampista'),
			('Andres', 'Iniesta', 34, 'España', 'FC Barcelona', 'Mediocampista'),
			('Saul', 'Ñiguez', 23, 'España', 'Atletico Madrid', 'Mediocampista'),
			('Koke', NULL, 26, 'España', 'Atletico Madrid', 'Mediocampista'),
			('Thiago', 'Alcantara', 27, 'España', 'Bayern Munich', 'Mediocampista'),
			('Lucas', 'Vazquez', 26, 'España', 'Real Madrid', 'Mediocampista'),
			('Marco', 'Asensio', 21, 'España', 'Real Madrid', 'Mediocampista'),
			('David', 'Silva', 32, 'España', 'Manchester City', 'Mediocampista'),
			('Isco', 'Alarcon', 26, 'España', 'Real Madrid', 'Mediocampista'),
			('Rodrigo', NULL, 27, 'España', 'Valencia', 'Delantero'),
			('Iago', 'Aspas', 30, 'España', 'Celta de Vigo', 'Delantero'),
			('Diego', 'Costa', 29, 'España', 'Atletico Madrid', 'Delantero'),
			('Yassine', 'Bounou', 27, 'Marruecos', 'Girona', 'Arquero'),
			('Munir', 'Mohamedi', 29, 'Marruecos', 'Numancia', 'Arquero'),
			('Ahmed', 'Reda Tagnaouti', 22, 'Marruecos', 'Ittihad Tanger', 'Arquero'),
			('Achraf', 'Hakimi', 19, 'Marruecos', 'Real Madrid', 'Defensor'),
			('Hamza', 'Mendyl', 20, 'Marruecos', 'Lille', 'Defensor'),
			('Manuel', 'da Costa', 32, 'Marruecos', 'Estambul Basaksehir', 'Defensor'),
			('Mehdi', 'Benatia', 31, 'Marruecos', 'Juventus FC', 'Defensor'),
			('Romain', 'Saiss', 28, 'Marruecos', 'Wolverhampton', 'Defensor'),
			('Nabil', 'Dirar', 32, 'Marruecos', 'Fenerbahce', 'Defensor'),
			('Hakim', 'Ziyech', 25, 'Marruecos', 'Ajax FC', 'Mediocampista'),
			('Karim', 'El Ahmadi', 33, 'Marruecos', 'Feyenoord', 'Mediocampista'),
			('Younes', 'Belhanda', 28, 'Marruecos', 'Galatasaraay', 'Mediocampista'),
			('Faycal', 'Fajr', 29, 'Marruecos', 'Getafe', 'Mediocampista'),
			('Mbark', 'Boussofa', 33, 'Marruecos', 'Al-Jazira', 'Mediocampista'),
			('Youssef', 'Ait Bennasser', 21, 'Marruecos', 'Caen', 'Mediocampista'),
			('Nordin', 'Amrabat', 31, 'Marruecos', 'Leganés', 'Mediocampista'),
			('Amine', 'Harit', 20, 'Marruecos', 'Schalke 04', 'Mediocampista'),
			('Sofyan', 'Amrabat', 21, 'Marruecos', 'Feyenoord', 'Mediocampista'),
			('Mehdi', 'Carcela-Gonzalez', 28, 'Marruecos', 'Standard Liege', 'Mediocampista'),
			('Ayoub', 'El Kaabi', 24, 'Marruecos', 'Renaissance de Berkane', 'Delantero'),
			('Kahlid', 'Boutaib', 31, 'Marruecos', 'Yeni Malatyaspor', 'Delantero'),
			('Youssef', 'En-Nesyri', 21, 'Marruecos', 'Málaga', 'Delantero'),
			('Aziz', 'Bouhaddouz', 31, 'Marruecos', 'St. Pauli', 'Delantero'),
			('Alireza', 'Beiranvand', 25, 'Irán', 'Persepolis', 'Arquero'),
			('Mohammad', 'Rashid Mazaheri', 29, 'Irán', 'Zob Ahan', 'Arquero'),
			('Amir', 'Abedzadeh', 25, 'Irán', 'Maritimo', 'Arquero'),
			('Ehsan', 'Hajsafi', 28, 'Irán', 'Olympiacos', 'Defensor'),
			('Rouzbeh', 'Cheshmi', 24, 'Irán', 'Esteghlal', 'Defensor'),
			('Milad', 'Mohammadi', 25, 'Irán', 'Ajmat Grozni', 'Defensor'),
			('Mohammed', 'Reza Khanzadeh', 27, 'Irán', 'Padideh', 'Defensor'),
			('Pejman', 'Montazeri', 34, 'Irán', 'Esteghlal', 'Defensor'),
			('Majid', 'Hosseini', 21, 'Irán', 'Esteghlal', 'Defensor'),
			('Ramin', 'Rezaeian', 28, 'Irán', 'Oostende', 'Defensor'),
			('Mehdi', 'Torabi', 23, 'Irán', 'Saipa', 'Mediocampista'),
			('Saeid', 'Ezatolahi', 21, 'Irán', 'Ammkar Perm', 'Mediocampista'),
			('Masoud', 'Shojaei', 34, 'Irán', 'AEK Atenas', 'Mediocampista'),
			('Omid', 'Ebrahimi', 30, 'Irán', 'Esteghlal', 'Mediocampista'),
			('Vahid', 'Amiri', 30, 'Irán', 'Persepolis', 'Mediocampista'),
			('Morteza', 'Pouraliganji', 26, 'Irán', 'Al-Sadd', 'Delantero'),
			('Karim', 'Ansarifard', 28, 'Irán', 'Olympiacos', 'Delantero'),
			('Saman', 'Ghoddos', 24, 'Irán', 'Ostersund', 'Delantero'),
			('Reza', 'Ghoochannejhad', 30, 'Irán', 'Heerenveen', 'Delantero'),
			('Mehdi', 'Taremi', 25, 'Irán', 'Al-Gharafa', 'Delantero'),
			('Alireza', 'Jahanbakhsh', 24, 'Irán', 'AZ Alkmaar', 'Delantero'),
			('Sardar', 'Azmoun', 23, 'Irán', 'Rubin Kazan', 'Delantero'),
			('Ashkan', 'Dejagah', 31, 'Irán', 'Nottingham Forest', 'Delantero'),
			('Hugo', 'Lloris', 31, 'Francia', 'Tottenham', 'Arquero'),
			('Benjamin', 'Pavard', 22, 'Francia', 'Stuttgart', 'Defensor'),
			('Presnel', 'Kimpembe', 22, 'Francia', 'Paris Saint Germain', 'Defensor'),
			('Raphael', 'Varane', 25, 'Francia', 'Real Madrid', 'Defensor'),
			('Samuel', 'Umtiti', 24, 'Francia', 'FC Barcelona', 'Defensor'),
			('Paul', 'Pogba', 25, 'Francia', 'Manchester United', 'Mediocampista'),
			('Antoine', 'Griezmann', 27, 'Francia', 'Atletico Madrid', 'Delantero'),
			('Thomas', 'Lemar', 22, 'Francia', 'Monaco', 'Delantero'),
			('Olivier', 'Giroud', 31, 'Francia', 'Chelsea FC', 'Delantero'),
			('Kylian', 'Mbappe', 19, 'Francia', 'Paris Saint Germain', 'Delantero'),
			('Ousmane', 'Dembelé', 21, 'Francia', 'FC Barcelona', 'Delantero'),
			('Corentin', 'Tolisso', 23, 'Francia', 'Bayern Munich', 'Mediocampista'),
			('NGolo', 'Kante', 27, 'Francia', 'Chelsea FC', 'Mediocampista'),
			('Blaise', 'Matuidi', 31, 'Francia', 'Juventus FC', 'Mediocampista'),
			('Steven', 'NZonzi', 29, 'Francia', 'Chelsea FC', 'Mediocampista'),
			('Steve', 'Mandanda', 33, 'Francia', 'Olympique Marseille', 'Arquero'),
			('Adil', 'Rami', 32, 'Francia', 'Olympique Marseille', 'Defensor'),
			('Nabil', 'Fekir', 24, 'Francia', 'Olympique Lyon', 'Delantero'),
			('Djibril', 'Sidibe', 25, 'Francia', 'Monaco', 'Defensor'),
			('Florian', 'Thauvin', 25, 'Francia', 'Olympique Marseille', 'Delantero'),
			('Lucas', 'Hernandez', 22, 'Francia', 'Atletico Madrid', 'Defensor'),
			('Benjamin', 'Mendy', 23, 'Francia', 'Manchester City', 'Defensor'),
			('Alphonse', 'Areola', 25, 'Francia', 'Paris Saint Germain', 'Arquero'),
			('Igor', 'Akinfeev', 32, 'Rusia', 'CSKA Moscu', 'Arquero'),
			('Mario', 'Fernandes', 27, 'Rusia', 'CSKA Moscu', 'Defensor'),
			('Ilia', 'Kutepov', 24, 'Rusia', 'Spartak Moscu', 'Defensor'),
			('Seguei', 'Ignasevich', 38, 'Rusia', 'CSKA Moscu', 'Defensor'),
			('Denis', 'Cheryshev', 29, 'Rusia', 'Ajmat Grozni', 'Defensor'),
			('Daler', 'Kuziaiev', 27, 'Rusia', 'Villareal', 'Mediocampista'),
			('Yuri', 'Gazinski', 25, 'Rusia', 'Zenit de San Petersburgo', 'Mediocampista'),
			('Alan', 'Dzagoev', 28, 'Rusia', 'Krasnodar', 'Mediocampista'),
			('Fiodor', 'Smolov', 27, 'Rusia', 'CSKA Moscu', 'Mediocampista'),
			('Roman', 'Zobnin', 28, 'Rusia', 'Krasnodar', 'Delantero'),
			('Andrei', 'Luniov', 24, 'Rusia', 'Spartak Moscu', 'Arquero'),
			('Fiodor', 'Kudriashov', 26, 'Rusia', 'Zenit de San Petersburgo', 'Mediocampista'),
			('Vladimir', 'Granat', 31, 'Rusia', 'Rubin Kazan', 'Defensor'),
			('Aleksei', 'Miranchuk', 31, 'Rusia', 'Rubin Kazan', 'Defensor'),
			('Anton', 'Miranchuk', 22, 'Rusia', 'Lokomotiv Moscu', 'Mediocampista'),
			('Yuri', 'Zhirkov', 22, 'Rusia', 'Lokomotiv Moscu', 'Mediocampista'),
			('Aleksandr', 'Samedov', 22, 'Rusia', 'CSKA Moscu', 'Mediocampista'),
			('Aleksandr', 'Golovin', 34, 'Rusia', 'Zenit de San Petersburgo', 'Mediocampista'),
			('Vladimir', 'Gabulov', 34, 'Rusia', 'Brugges', 'Arquero'),
			('Aleksandr', 'Yerojin', 28, 'Rusia', 'Zenit de San Petersburgo', 'Mediocampista'),
			('Artiom', 'Dziuba', 29, 'Rusia', 'Arsenal Tula', 'Delantero'),
			('Igor', 'Smolnikov', 29, 'Rusia', 'Zenit de San Petersburgo', 'Defensor'),
			('Fernando', 'Muslera', 31, 'Uruguay', 'Galatasaraay', 'Arquero'),
			('Martin', 'Campaña', 29, 'Uruguay', 'Independiente', 'Arquero'),
			('Martin', 'Silva', 35, 'Uruguay', 'Vasco da Gama', 'Arquero'),
			('Jose', 'Gimenez', 23, 'Uruguay', 'Atletico Madrid', 'Defensor'),
			('Diego', 'Godin', 32, 'Uruguay', 'Atletico Madrid', 'Defensor'),
			('Guillermo', 'Varela', 25, 'Uruguay', 'Peñarol', 'Defensor'),
			('Gaston', 'Silva', 24, 'Uruguay', 'Independiente', 'Defensor'),
			('Maxi', 'Pereira', 34, 'Uruguay', 'Porto', 'Defensor'),
			('Sebastian', 'Coates', 27, 'Uruguay', 'Sporting Lisboa', 'Defensor'),
			('Martin', 'Caceres', 31, 'Uruguay', 'Lazio', 'Defensor'),
			('Carlos', 'Sanchez', 33, 'Uruguay', 'Monterrey', 'Mediocampista'),
			('Rodrigo', 'Bentancur', 20, 'Uruguay', 'Juventus FC', 'Mediocampista'),
			('Cristian', 'Rodriguez', 32, 'Uruguay', 'Peñarol', 'Mediocampista'),
			('Nahitan', 'Nandez', 22, 'Uruguay', 'Boca Juniors', 'Mediocampista'),
			('Lucas', 'Torreira', 22, 'Uruguay', 'Sampdoria', 'Mediocampista'),
			('Matias', 'Vecino', 26, 'Uruguay', 'Inter', 'Mediocampista'),
			('Diego', 'Laxalt', 25, 'Uruguay', 'Genoa', 'Mediocampista'),
			('Luis', 'Suarez', 31, 'Uruguay', 'FC Barcelona', 'Delantero'),
			('Giorgian', 'de Arrascaeta', 24, 'Uruguay', 'Cruzeiro', 'Delantero'),
			('Christian', 'Stuani', 31, 'Uruguay', 'Girona', 'Delantero'),
			('Maxi', 'Gomez', 21, 'Uruguay', 'Celta de Vigo', 'Delantero'),
			('Jonathan', 'Urretaviscaya', 28, 'Uruguay', 'Monterrey', 'Delantero'),
			('Edinson', 'Cavani', 31, 'Uruguay', 'Paris Saint Germain', 'Delantero'),
			('Essam', 'El-Hadary', 45, 'Egipto', 'Al-Taawoun', 'Arquero'),
			('Sherif', 'Ekramy', 34, 'Egipto', 'Al-Ahly', 'Arquero'),
			('Mohamed', 'El-Shenawy', 29, 'Egipto', 'Al-Ahly', 'Arquero'),
			('Ali', 'Gabr', 29, 'Egipto', 'West Bromwich', 'Defensor'),
			('Ahmed', 'Al-Muhammadi', 30, 'Egipto', 'Aston Villa', 'Defensor'),
			('Ahmed', 'Hegazy', 27, 'Egipto', 'West Bromwich', 'Defensor'),
			('Ahmed', 'Fathy', 33, 'Egipto', 'Al-Ahly', 'Defensor'),
			('Ayman', 'Ashraf', 27, 'Egipto', 'Al-Ahly', 'Defensor'),
			('Mohamed', 'Abdel-Shafy', 32, 'Egipto', 'Al-Fateh', 'Defensor'),
			('Mahmoud', 'Hamdy', 23, 'Egipto', 'Zamalek', 'Defensor'),
			('Saad', 'Samir', 29, 'Egipto', 'Al-Ahly', 'Defensor'),
			('Omar', 'Gaber', 26, 'Egipto', 'Los Angeles FC', 'Mediocampista'),
			('Sam', 'Morsy', 25, 'Egipto', 'Wigan Athletic', 'Mediocampista'),
			('Tarek', 'Ahmed', 29, 'Egipto', 'Zamalek', 'Mediocampista'),
			('Mohamed', 'Elneny', 25, 'Egipto', 'Arsenal FC', 'Mediocampista'),
			('Abdallah', 'Said', 32, 'Egipto', 'KuPS Kuopio', 'Mediocampista'),
			('Trezeguet', NULL, 23, 'Egipto', 'Kasimpasa', 'Mediocampista'),
			('Marwan', 'Mohsen', 29, 'Egipto', 'Al-Ahly', 'Delantero'),
			('Mohamed', 'Salah', 25, 'Egipto', 'Liverpool FC', 'Delantero'),
			('Kahraba', NULL, 24, 'Egipto', 'Al-Ittihad', 'Delantero'),
			('Ramadan', 'Sobhi', 21, 'Egipto', 'Stoke City', 'Delantero'),
			('Shikabala', NULL, 32, 'Egipto', 'Al-Raed', 'Delantero'),
			('Amr', 'Warda', 24, 'Egipto', 'Atromitos', 'Delantero')
